In [36]:
import pandas as pd

In [37]:
pip install xlrd

Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Requirement already satisfied: xlrd in /Users/daniela/Desktop/Proyecto EDA/analisis_marketing/venv/lib/python3.9/site-packages (2.0.2)
Note: you may need to restart the kernel to use updated packages.

In [38]:
!pip install openpyxl

Looking in indexes: https://pypi.python.org/simple, https://pypi.apple.com/simple
Requirement already satisfied: openpyxl in /Users/daniela/Desktop/Proyecto EDA/analisis_marketing/venv/lib/python3.9/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /Users/daniela/Desktop/Proyecto EDA/analisis_marketing/venv/lib/python3.9/site-packages (from openpyxl) (2.0.0)

In [39]:
xls = pd.ExcelFile('/Users/daniela/Desktop/Proyecto EDA/analisis_marketing/DataRaw/DatosProyecto/customer-details.xlsx')
print(xls.sheet_names)

['2012', '2013', '2014']

In [40]:
file_path = '/Users/daniela/Desktop/Proyecto EDA/analisis_marketing/DataRaw/DatosProyecto/customer-details.xlsx'

sheets = pd.read_excel(file_path, sheet_name=None)

dfs = []

for sheet_name, df in sheets.items():
    df['Dt_Customer'] = pd.to_datetime(df['Dt_Customer'])
    df['Join_Year'] = df['Dt_Customer'].dt.year
    dfs.append(df)
    
df_combined = pd.concat(dfs, ignore_index=True)
df_combined.head()

,Unnamed: 0,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,Join_Year
0,0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,2012
1,1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,2012
2,2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,2012
3,3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,2012
4,4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,2012

In [42]:
df_combined.shape

(43170, 8)

In [43]:
df_combined.columns

Index(['Unnamed: 0', 'Income', 'Kidhome', 'Teenhome', 'Dt_Customer',
       'NumWebVisitsMonth', 'ID', 'Join_Year'],
      dtype='object')

In [44]:
df_combined.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 43170 entries, 0 to 43169
Data columns (total 8 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Unnamed: 0         43170 non-null  int64
 1   Income             43170 non-null  int64
 2   Kidhome            43170 non-null  int64
 3   Teenhome           43170 non-null  int64
 4   Dt_Customer        43170 non-null  datetime64[ns]
 5   NumWebVisitsMonth  43170 non-null  int64
 6   ID                 43170 non-null  object
 7   Join_Year          43170 non-null  int32
dtypes: datetime64[ns](1), int32(1), int64(5), object(1)
memory usage: 2.5+ MB

In [45]:
df = df_combined.copy()

In [46]:
df.drop(columns="Unnamed: 0", inplace=True)
df.head()

,Income,Kidhome,Teenhome,Dt_Customer,NumWebVisitsMonth,ID,Join_Year
0,161770,1,0,2012-04-04,29,089b39d8-e4d0-461b-87d4-814d71e0e079,2012
1,85477,1,1,2012-12-30,7,e9d37224-cb6f-4942-98d7-46672963d097,2012
2,147233,1,1,2012-02-02,5,3f9f49b5-e410-4948-bf6e-f9244f04918b,2012
3,121393,1,2,2012-12-21,29,9991fafb-4447-451a-8be2-b0df6098d13e,2012
4,63164,1,2,2012-06-20,20,eca60b76-70b6-4077-80ba-bc52e8ebb0eb,2012

In [47]:
df.to_csv('../Data/data_transformacion_limpieza_customer.csv', index=False)